version: '3'

services:
  web:
    container_name: 'go_dorkly_api'
    build: .
    ports: 
      - '7000:8080'
    volumes: 
      - .:/usr/app
    depends_on:
      - db
    links: 
      - db:database
  db:
    image: 'postgres'
    env_file: './database.ENV'
    ports: 
    - '7001:5432'
